server.port = 8081
# Change base URL for all APIs

#Oracle DB connection properties
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable live reload
spring.devtools.livereload.enabled=true

# Disable caching of templates (for Thymeleaf, etc.)
spring.thymeleaf.cache=false
